

ALTER TABLE CageVisits
--ADD CONSTRAINT cageID
ADD FOREIGN KEY (cageID)
REFERENCES Cages (cageID)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE CageVisits
--ADD CONSTRAINT memberID
ADD FOREIGN KEY (memberID)
REFERENCES Members (memberID)
ON DELETE CASCADE
ON UPDATE CASCADE;
